In [1]:
True+False

1

In [12]:
first_string = 'python'
second_string = 'is a powerful'
third_string = 'language'
print(first_string+second_string+third_string)
type(first_string)

pythonis a powerfullanguage


str

In [5]:
print(first_string+second_string+third_string)

pythonis a powerfullanguage


In [35]:
import keywords



ModuleNotFoundError: No module named 'keywords'

In [6]:
True+False

1

In [7]:
True*3

3

In [9]:
print('*'*60)

************************************************************


In [10]:
True is False

False

In [11]:
10==15

False

In [13]:
list("sadaf")

['s', 'a', 'd', 'a', 'f']

In [15]:
list('1234')

['1', '2', '3', '4']

In [16]:
print ('day'+"2")

day2


In [2]:
a=10
b=15
c=a+b
print(c)
print('c\n'*9     )

25
c
c
c
c
c
c
c
c
c



list

In [4]:
marks = [35,45,56,67,78,89,99]
marks

[35, 45, 56, 67, 78, 89, 99]

In [20]:
c_marks=marks.copy()

In [21]:
c_marks

[35, 45, 56, 67, 78, 89, 99]

In [22]:
marks[2:5]

[56, 67, 78]

In [23]:
marks[ :5]

[35, 45, 56, 67, 78]

In [6]:
marks.append(43)
marks

[35, 45, 56, 67, 78, 89, 99, 43, 43]

In [7]:
marks.pop()
marks

[35, 45, 56, 67, 78, 89, 99, 43]

In [8]:
marks .extend([54,52,57])

In [9]:
marks

[35, 45, 56, 67, 78, 89, 99, 43, 54, 52, 57]

In [10]:
marks.count(57)

1

In [11]:
marks.index(67)

3

In [12]:
marks.remove(57)

In [13]:
marks

[35, 45, 56, 67, 78, 89, 99, 43, 54, 52]

In [14]:
marks.sort()
marks
marks.reverse()
marks

[99, 89, 78, 67, 56, 54, 52, 45, 43, 35]

In [15]:
marks.sort(reverse=1)
marks

[99, 89, 78, 67, 56, 54, 52, 45, 43, 35]

In [16]:
marks.insert(3,53)
marks

[99, 89, 78, 53, 67, 56, 54, 52, 45, 43, 35]

In [17]:
len(marks)

11

In [18]:
35 in marks
11 in marks
34 in marks

False

In [19]:
(89,99,76) in marks

False

In [3]:
x =[20,25,30,45,89,39,100,28]
for no in x:
    if no>=25 and no<=60:
        print(no)
       
            

25
30
45
39
28


In [ ]:
Dictionary

In [22]:
my_dict={'roll_no':123,'marks':[12,23,33],'subject':['computer','science','maths']}
my_dict['subject']

['computer', 'science', 'maths']

In [23]:
my_dict['subject'][2]

'maths'

In [25]:
my_dict['subject'][1].upper()

'SCIENCE'

In [26]:
my_dict['marks'][2]+= 30
my_dict['marks']

[12, 23, 63]

In [27]:
my_dict['year']='4th'
my_dict

{'roll_no': 123,
 'marks': [12, 23, 63],
 'subject': ['computer', 'science', 'maths'],
 'year': '4th'}

In [30]:
my_dict.update({'roll_no': 154})
my_dict

{'roll_no': 154,
 'marks': [12, 23, 63],
 'subject': ['computer', 'science', 'maths'],
 'year': '4th'}

In [31]:
my_dict.keys()

dict_keys(['roll_no', 'marks', 'subject', 'year'])

In [33]:
my_dict.values()

dict_values([154, [12, 23, 63], ['computer', 'science', 'maths'], '4th'])

In [34]:
my_dict.items()

dict_items([('roll_no', 154), ('marks', [12, 23, 63]), ('subject', ['computer', 'science', 'maths']), ('year', '4th')])

In [ ]:
branching if -else

In [41]:
item_1= 300
item_2= 15
if (item_1+ item_2)>=500:
    print('your item is elegible for free delivery')
else:
    extra=500-(item_1+item_2)
    print('please add', extra, 'amount of an item for free delivery')

please add 185 amount of an item for free delivery


In [59]:
student_marks=[45,66,65,30,89,99,55]
for marks in student_marks:
    if marks >= 60:
        if marks > 70:
            print('marks-','Distinction')
        else:
            print('marks-','first class')
    elif marks > 50 and marks < 60:
         print('marks-','second class')
    elif marks>= 35:
        print('marks-','pass')
    else:
        print('marks-',"fail-better luck next time")
            

marks- pass
marks- first class
marks- first class
marks- fail-better luck next time
marks- Distinction
marks- Distinction
marks- second class


In [ ]:
RANGE

In [60]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [61]:
list(range(100,400,30))

[100, 130, 160, 190, 220, 250, 280, 310, 340, 370]

In [63]:
list(range(500,-5,-25))

[500,
 475,
 450,
 425,
 400,
 375,
 350,
 325,
 300,
 275,
 250,
 225,
 200,
 175,
 150,
 125,
 100,
 75,
 50,
 25,
 0]

In [77]:
for num in range(2,5):
    print('multiplication of', num)
    for i in range(1,11):
        print( num*i)
        if i==10:
            print("\n")
else:
    print ('*'*10)
    print('end of table')

multiplication of 2
2
4
6
8
10
12
14
16
18
20


multiplication of 3
3
6
9
12
15
18
21
24
27
30


multiplication of 4
4
8
12
16
20
24
28
32
36
40


**********
end of table


In [ ]:
WHILE LOOP

In [78]:
import time
result= time.localtime()
print(result)

time.struct_time(tm_year=2023, tm_mon=4, tm_mday=27, tm_hour=20, tm_min=11, tm_sec=20, tm_wday=3, tm_yday=117, tm_isdst=0)


In [79]:
while True:
    result = time.localtime()
    if result.tm_min==14 and result.tm_hour==20:
        print('wake up sweeti')
        break

wake up sweeti


In [84]:
stu=['sadaf','tabshir','sufiyan','shavez','rinky','suffu']
for name in enumerate(stu):
    print(name)


(0, 'sadaf')
(1, 'tabshir')
(2, 'sufiyan')
(3, 'shavez')
(4, 'rinky')
(5, 'suffu')


In [88]:
for name in enumerate(stu,200):
    print(name)

(200, 'sadaf')
(201, 'tabshir')
(202, 'sufiyan')
(203, 'shavez')
(204, 'rinky')
(205, 'suffu')


In [ ]:
ZIP & UNZIP

In [97]:
stu=['sadaf','tabshir','sufiyan','shavez','rinky','suffu']
marks=[99,98,99,89,98,90,91,92]
stu_details=list(zip(stu,marks))
stu_details

[('sadaf', 99),
 ('tabshir', 98),
 ('sufiyan', 99),
 ('shavez', 89),
 ('rinky', 98),
 ('suffu', 90)]

In [ ]:
UNZIP

In [98]:
stu,marks =zip(*stu_details)

In [102]:
stu


('sadaf', 'tabshir', 'sufiyan', 'shavez', 'rinky', 'suffu')

In [103]:
marks

(99, 98, 99, 89, 98, 90)

In [ ]:
BREAK AND CONTINUE

In [90]:
stu=['sadaf','tabshir','sufiyan','shavez','rinky','suffu']
for name in stu:
    if name =="rinky":
        break
    print(name)

sadaf
tabshir
sufiyan
shavez


In [91]:
stu=['sadaf','tabshir','sufiyan','shavez','rinky','suffu']
for name in stu:
    if name =="rinky":
        continue
    print(name)

sadaf
tabshir
sufiyan
shavez
suffu


In [ ]:
FUNCTIONS

In [104]:
def greeting(name):
    print('hello',name)
greeting('good morning')

hello good morning


In [109]:
def salary_incr(fixed_salary,house_rent):
    total_salary=(fixed_salary + house_rent)
    if total_salary>=7000:
        return total_salary+2000
    else:
        return total_salary

In [110]:
print("your new salary=",salary_incr(4700,5000))

your new salary= 11700


In [14]:
def used_car_price(car_year,car_brand,kmeters):
    if car_year == 2020:
        if 10000<kmeters<=15000:
            if car_brand=='honda amaze':
                print('690000 -750000')
            elif car_brand == 'hyundai creta':
                print('94500-108000')
            else:
                print('no stock right now, please visit after few days')
        elif 15001<kmeters<=25000:
            if car_brand =='honda amaze':
                print('550000-600000')
            elif car_brand =="hyundai creta":
                print('845000-980000')
            else:
                print('no stock right now, please visit after few days')
        else:
            print('no stocks')
    elif car_year ==2021:
        if 10000<kmeters<=15000:
            if car_brand=='honda amaze':
                print('790000-850000')
            elif car_brand=='hyundai creta':
                print('1045000-1180000')
            else:
                print('no stock right now, please visit after few days')
        else:
            print('no stock right now, please visit after few days')
    else: 
        print('sorry , we dont keep car older than 2020')
        
car_brand=input('enter car brand?')
kmeters=input('enter km driven?')
car_year=input('enter manufacturing year?')
used_car_price=(car_year,car_brand,kmeters)
print(used_car_price)
        
            
                   
                  
                  
                  
                  
                  

enter car brand?honda amaze
enter km driven?14000
enter manufacturing year?2021
('2021', 'honda amaze', '14000')


In [6]:
used_car_price(2021,'hyundai creta',14000)

1045000-1180000


In [3]:
used_car_price(2020,'honda amaze',23000)

550000-600000


In [ ]:
kwarg**

In [4]:
def my(**kwargs):
    for key,value in kwargs.items():
        print(value,end=" ")
        

In [7]:
my(student=["sadaf","sufiyan"],marks=[99,98,])

['sadaf', 'sufiyan'] [99, 98] 

# MAP_FILTER

In [2]:
def grace(marks):
    if marks==32:
        return (marks+3)
    elif marks ==33:
        return(marks+2)
    elif marks==34:
        return(marks+1)
    else:
        return marks
score=[45,32,31,33,15,36,89]
print(list(map(grace,score)))

[45, 35, 31, 35, 15, 36, 89]


# USER input

In [10]:
maths=int(input('enter maths marks?:'))
science=int(input('enter science marks?:'))
total=maths+science
print('total',total)

enter maths marks?:99
enter science marks?:98
total 197


In [1]:
name= input('enter your name?:')
if name.isalpha():
    print('Alphabet',name)
else:
    print('enter only alphabet')

enter your name?:sadaf
Alphabet sadaf


# try and except

In [3]:
def mob_no():
    while True:
        val= int(input('enter mobile number?'))
        try:
            if len(str( val))!=10:
                print('plz enter 10 digit no')
                continue
            else:
                print('thank you')
        except:
            print("looks like u do not enter a valid no")
        finally:
            print("user entered",val)
                
                

# inheritance

In [ ]:
mob_no(


In [14]:
class Account:
    def __init__(self,
                name     =input('enter your name'),
                last_name =input('enter last name'),
                city     =input('enter city name')
                ,user_id =input('enter preffered user id'),
                password =input('choose your password'),
                phone    =input('enter phone no')):
  

        self.name      = name
        self.last_name = last_name
        self.city      = city
        self.user_id   = user_id
        self.password  = password
        self.phone     = phone
    def login(self):
        while True:
            signin= input('email id')
            password=input('password')
            if signin == self.user_id and password ==self.password:
                print('successfully logged in')
                break
            else:
                print('user id and password invalid')
                continue
    
    

enter your namesadaf
enter last nameshamim
enter city nameriyadh
enter preffered user idsadaf12
choose your password1234
enter phone no123456


In [15]:
bank= Account()

In [16]:
bank.login()

email idsadaf
password1234
user id and password invalid
email idsadaf12
password1234
successfully logged in


In [29]:
class User_Account (Account):
    def __init__(self,acc_number,balance,*args):
        super (User_Account,self).__init__(*args)
        self.acc_number  = acc_number
        self.balance     = balance
        
    def user_details(self):
        while True:
            account = int(input('enter your account number: '))
            if account== self.acc_number:
                print("Name",self.name)
                print("Account number",self.acc_number)
                print("your balance", self.balance)
                break   
            else:
                print("Account number is not valid")
                continue
        
    def deposit(self):
        print("your previous balance=",self.balance)
        add_cash =int(input("Deposit cash"))
        self.balance+=add_cash
        print("\n HDFC bank:RS",add_cash,"deposited to your account",self.acc_number,"your current balance is", self.balance)
    def transfer(self):
        print("your previous balance=", self.balance)
        
        
        
        withdraw= int(input("enter the amount you want to transfer"))
        if withdraw<=self.balance:
            self.balance-=withdraw
            print('\n HDFC BANK Rs',withdraw,'withdraw from your account', self.acc_number,'and your current balance is', self.balance)
            
        else:
            print('\n ALLERT,HELLO! you dont have sufficient balance')
            
                

In [30]:
bank_details=User_Account(123467,10000)

In [31]:
bank_details.user_details()

enter your account number: 123467
Name sadaf
Account number 123467
your balance 10000


In [32]:
bank_details.deposit()

your previous balance= 10000
Deposit cash5900

 HDFC bank:RS 5900 deposited to your account 123467 your current balance is 15900


In [33]:
bank_details.transfer()


your previous balance= 15900
enter the amount you want to transfer2500

 HDFC BANK Rs 2500 withdraw from your account 123467 and your current balance is 13400


In [ ]:
encapsulation

In [36]:
class Tyres:
    def __init__(self, branch, belted_bias,opt_pressure):
        self.branch  = branch
        self.belted_bias  = belted_bias
        self.opt_pressure  = opt_pressure
        
    def __str__(self):
        return('tyres:\n\tbranch: '+self.branch+'\n belted_bias: '+str(self.belted_bias)+'\n\ optimal pressure: '+str(self.opt_pressure))
class Engine:
    def __init__(self,fuel_type,noise_level):
        self.fuel_type  = fuel_type
        self.noise_level = noise_level
        
    def __str__(self):
        return('Engine \n\ tfuel type: '+self.fuel_type+'\n\ tnoise level: ' +str(self.noise_level))
    
class Body:
    def __init__(self,size):
        self.size =size
    def __str__(self):
        return('Body :\n\ tsize :'+self.size)
    
class Car:
    def __init__(self,tyres,engine,body):
        self.tyres =tyres
        self.engine= engine
        self.body  = body
    def __str__(self):
        return str(self.tyres)+'\n'+str(self.engine)+'\n'+str(self.body)

t =Tyres( 'MRF',True,34)
e= Engine('Petrol',23)
b =Body('SUV')

c=Car(t,e,b)

print(c)
    
    
    
        

tyres:
	branch: MRF
 belted_bias: True
\ optimal pressure: 34
Engine 
\ tfuel type: Petrol
\ tnoise level: 23
Body :
\ tsize :SUV


In [ ]:
NUMPY ARRAY

In [1]:
import numpy as np

In [38]:
print (dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [39]:
np.dot([3,4],[4,78])

324

In [40]:
np.sqrt(45)

6.708203932499369

In [41]:
np.square(5)

25

In [42]:
np.min([23,67,89,67,21,20,14])

14

In [43]:
np.max([67,99,78,65])

99

In [44]:
np.ceil(65.8976)

66.0

In [46]:
a=np.array([5,8,9,0])

In [47]:
type(a)

numpy.ndarray

In [53]:
b=np.asarray(a) # copy  array as array
print(b)

[5 8 9 0]


In [54]:
np.array([1,3,6] , dtype=float)

array([1., 3., 6.])

In [55]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print('type class:',type(mat))
print('here is the matrix\n----\n',mat,'\n-----\n')
print('dimension of matrix:',mat.ndim)
print('size:',mat.size)
print('shape:',mat.shape)
print('data type:',mat.dtype)

type class: <class 'numpy.ndarray'>
here is the matrix
----
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----

dimension of matrix: 2
size: 9
shape: (3, 3)
data type: int32


In [57]:
a= np.arange(2,10.5,.6)
print(a)

[ 2.   2.6  3.2  3.8  4.4  5.   5.6  6.2  6.8  7.4  8.   8.6  9.2  9.8
 10.4]


In [58]:
a[ : :-1] # reverse order

array([10.4,  9.8,  9.2,  8.6,  8. ,  7.4,  6.8,  6.2,  5.6,  5. ,  4.4,
        3.8,  3.2,  2.6,  2. ])

In [59]:
np.arange(50,-1,-5) #every 5th no from 50 in reverse order

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [61]:
np.linspace(10,40,5) # linearly seperable

array([10. , 17.5, 25. , 32.5, 40. ])

In [5]:
np.linspace(2.0,3.0,num=4,endpoint=False,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75]), 0.25)

In [2]:
np.linspace(2.0,3.0,num=4,endpoint=True,retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [8]:
np.linspace(3.897655,5.7887,5,retstep=True)

(array([3.897655  , 4.37041625, 4.8431775 , 5.31593875, 5.7887    ]),
 0.47276125000000013)

# MATRIX CREATION

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
67*np.ones((6,5))

array([[67., 67., 67., 67., 67.],
       [67., 67., 67., 67., 67.],
       [67., 67., 67., 67., 67.],
       [67., 67., 67., 67., 67.],
       [67., 67., 67., 67., 67.],
       [67., 67., 67., 67., 67.]])

In [14]:
np.arange(30).reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [20]:
np.random.seed(4)
np.random.rand(3,3)# uniform distribution

array([[0.96702984, 0.54723225, 0.97268436],
       [0.71481599, 0.69772882, 0.2160895 ],
       [0.97627445, 0.00623026, 0.25298236]])

In [22]:
np.random.randn(3,3)# normal distribution

array([[ 0.20218012,  0.16951775, -0.71522547],
       [ 0.52533388, -0.74738768,  0.74981904],
       [-2.4598148 ,  0.03600369,  0.72612944]])

In [24]:
np.random.randint(5,23,10)  #used to generate otp

array([12, 14, 21, 20,  9, 16, 13, 10, 13, 12])

In [25]:
while True:
    otp= np.random.randint(1000,10000,1)
    print( 'your opt is ',otp)
    user_otp= int(input('enter the otp'))
    if otp==user_otp:
        print('login successful')
        break
    else:
        print('invalid otp')
        continue

your opt is  [8652]
enter the otp56788
invalid otp
your opt is  [7687]
enter the otp7687
login successful


In [1]:
from numpy.random import randint as ri

In [15]:
m=ri(1,100,25).reshape(5,5)
print(m)

[[22 21 34 43 80]
 [27 71 78 38 35]
 [84 94  4 48 65]
 [10  5 80 99 76]
 [ 5 69 32 82 42]]


In [6]:
np.sort(m)

array([[18, 45, 55, 60, 97],
       [32, 66, 78, 95, 96],
       [10, 25, 54, 67, 75],
       [36, 48, 70, 76, 92],
       [ 4, 47, 56, 56, 67]])

In [ ]:
np.sort(m,axis=0)# column wise sorting

In [13]:
print(m.min(), m.max())

4 97


In [17]:
emp_sal= ri(8,70,10)
emp_sal

array([33,  8, 41, 28, 56, 11,  9, 25, 33, 34])

In [18]:
np.where(emp_sal<25) # will give the index

(array([1, 5, 6], dtype=int64),)

In [19]:
emp_sal[np.where(emp_sal<25)] # wll give the actual data

array([ 8, 11,  9])

In [20]:
np.clip(emp_sal,a_min=15, a_max=50)# set min and max using a_min, a_max

array([33, 15, 41, 28, 50, 15, 15, 25, 33, 34])

In [ ]:
INDEXING AND SLICING

In [25]:
arr=np.arange(13,30)
print("Array",arr)
print('element in 7th indexis:',arr[7])
arr[[2,4,8,10]]

Array [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
element in 7th indexis: 20


array([15, 17, 21, 23])

In [26]:
a=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(a)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
mat[1,[0,2]] # 1 st row then column selection

array([4, 6])

In [28]:
mat[1]

array([4, 5, 6])

In [29]:
mat[ : ,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [30]:
mat[1:3,1:2]

array([[5],
       [8]])

In [31]:
mat[0,1]=35 #update matrix
mat[2,2]=10
mat

array([[ 1, 35,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [32]:
mat

array([[ 1, 35,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [33]:
#subsetting
mat=np.array(ri(10,100,15)).reshape(3,5)
mat

array([[81, 15, 25, 83, 36],
       [11, 16, 64, 77, 54],
       [46, 59, 74, 83, 10]])

In [34]:
mat>50

array([[ True, False, False,  True, False],
       [False, False,  True,  True,  True],
       [False,  True,  True,  True, False]])

In [35]:
mat[mat>50]

array([81, 83, 64, 77, 54, 59, 74, 83])

In [37]:
mat=70
np.where(mat<68,'pass','fail')

array('fail', dtype='<U4')

In [40]:
a=ri(-10,50,100)
b=np.count_nonzero(a)
print(b)
print(a)

97
[-10  -4  18  -7   8  47  -2  26   8   0   9  40  -6  -3  20   6  42   6
  33   0   9  28  27  -6  25  36   4   5  36   2  19  40  41  26  19   9
  20  35  42  13  47  38  27  21   8   1  34  34  31  10  37  -3  22  49
  27  30  48  32  13  -2  35  -3  48  19  -1  43  17  39   4  46  14   2
  -6   4  29 -10  47  40  48  41  21   8   2  46  26   4  12   4  -6  29
  18  -8  29   9  41   6  46  -5   0   8]


In [44]:
a=np.random.randint(0,20,size=(3,4))
print(a)
a.ravel()


[[ 3 18 17  2]
 [15 14 19 13]
 [14 17 16 15]]


array([ 3, 18, 17,  2, 15, 14, 19, 13, 14, 17, 16, 15])

In [46]:
#universal function
mat1= np.array(ri(1,10,9)).reshape(3,3)
mat2= np.array(ri(1,10,9)).reshape(3,3)
print(mat1)
print(mat2)
print(mat1+mat2,'a')
print(mat1*mat2,'b')

[[6 1 2]
 [9 8 1]
 [7 5 3]]
[[9 3 6]
 [1 1 8]
 [6 6 6]]
[[15  4  8]
 [10  9  9]
 [13 11  9]] a
[[54  3 12]
 [ 9  8  8]
 [42 30 18]] b


In [ ]:
d